version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8976:80"
            - "8977:443"
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql



